version: "3.7"
services:
  portfolio-backend:
    build:
      context: portfolio_backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      ROCKET_ENV: development
      DATABASE_URL: postgres://portfolio:portfolio@postgres:5432/portfolio
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SECRET_KEY: ${SECRET_KEY}

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  portfolio-frontend:
    build:
      context: portfolio_frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - portfolio-backend

volumes:
  postgres_data:
