# Generated by Django 3.0.7 on 2020-06-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('short_description', models.TextField(max_length=1024)),
                ('long_description', models.TextField(max_length=4096)),
                ('watchers', models.IntegerField()),
                ('stargazers', models.IntegerField()),
                ('forks', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
