# Generated by Django 3.0.7 on 2020-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='recorded_at',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='repository',
            name='language',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
