# Generated by Django 3.0.7 on 2020-06-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200617_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorymetadata',
            name='watchers',
        ),
    ]
