# Generated by Django 3.0.7 on 2020-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_repositorymetadata_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorymetadata',
            name='forks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repositorymetadata',
            name='language',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='repositorymetadata',
            name='long_description',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='repositorymetadata',
            name='short_description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='repositorymetadata',
            name='stargazers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
