name: Build & Push

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      artifact-metadata: write
      attestations: write
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: den4200/shared-workflows/actions/build-container-image@ca978df0e1935438eddefd8b6068eaf101fb9a47
        with:
          password: ${{ github.token }}
