name: Build, Push, and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
        repository: den4200/portfolio_backend
        path: ./portfolio_backend
        dockerfile: ./portfolio_backend/Dockerfile
        tag_with_sha: true
        tag_with_ref: true

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
        repository: den4200/portfolio_frontend
        path: ./portfolio_frontend
        dockerfile: ./portfolio_frontend/Dockerfile
        tag_with_sha: true
        tag_with_ref: true
